# Generated by Django 4.1.7 on 2023-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
