# Generated by Django 4.1.7 on 2023-09-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='User',
            new_name='user',
        ),
    ]
