# Generated by Django 4.1.7 on 2023-09-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subjects_subject_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Subject_marks',
            new_name='SubjectMarks',
        ),
        migrations.RenameField(
            model_name='subjectmarks',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together={('student', 'subject')},
        ),
    ]
